[package]
name = "parser-generator-for-seatbelt2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {features = ["derive"], version="4.1.1"}
